DROP TABLE IF EXISTS EVENTS;

CREATE TABLE EVENTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  TYPE VARCHAR(250) NOT NULL,
  ACTOR_ID VARCHAR(250) NOT NULL,
  ACTOR_LOGIN VARCHAR(250) NOT NULL,
  ACTOR_AVATAR_URL VARCHAR(250) DEFAULT NULL,

  REPO_ID VARCHAR(250) NOT NULL,
  REPO_NAME VARCHAR(250) NOT NULL,
   REPO_URL VARCHAR(250) DEFAULT NULL,
   CREATED_AT DATE
);